#!/bin/sh

# import helpers
source `dirname $0`/helpers

# Install python
function install_python {
  if type "/usr/local/bin/pip3" > /dev/null; then
    einf "Python already installed... skipping"
    return
  fi

  einf "Installing python"
  brew install python3

  einf "Upgrading pip"
  pip3 install --upgrade pip

  einf "Installing virtualenv"
  pip3 install virtualenv
  pip3 install virtualenvwrapper

  rm -r virtualenvs
  mkdir virtualenvs
  ln -sF $DOTFILES/virtualenvs ~/.virtualenvs

  source /usr/local/bin/virtualenvwrapper.sh
  mkvirtualenv --python=`which python3` venv
}

askdo install_python "Install python?"
